env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  # - plugin:vue/essentioal
  # - "@vue/prettier"
parserOptions:
  ecmaVersion: 2020
plugins:
  - prettier
root: true
rules:
  prettier/prettier: warn
overrides:
  - files:
    - '*.js'
    - '*.vue'
    parserOptions:
      sourceType: module
  # - files:
  #   - "*.vue"
  #   extends:
  #     - plugin:vue/vue3-recommended
  #     # - "@vue/prettier"
  #   plugins:
  #     - vue
  #   parser: vue-eslint-parser
  #   parserOptions:
  #     parser: babel-eslint
  #     sourceType: module
  #     ecmaVersion: 2020
  #     ecmaFeatures:
  #       jsx: true